### ISSUE TITLE
When trying to upgrade data that doesn't exist, a python error is shown

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#1]
The issue happened when I included a configuration that didn't have a database tables but I selected I want to backup. Thus, before backing up, a check needs to be in place if the table exists. pg_table_exists() function in pg_utils can solve the issue.  The error is shown below. 

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 308, in login
    config_load_status = self.load_configuration_from_file()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 546, in load_configuration_from_file
    self.configuration_file_updater.backup_data()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\settings\config_file_updater.py", line 863, in backup_data
    data = export_data(social_tenure_entity)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\pg_utils.py", line 175, in export_data
    return _execute(t)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\pg_utils.py", line 380, in _execute
    result = conn.execute(sql,**kwargs)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "parcel" does not exist
LINE 1: SELECT * FROM parcel
                      ^
 'SELECT * FROM parcel' {}


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party\\fontTools']
```

**Comment by geonomad-consulting** [comment]
This is fixed.

**Comment by wondie** [comment]
I have confirmed this issue is fixed!

**Comment by geonomad-consulting** [comment]
via [commit](https://github.com/geonomad-consulting/stdm/commit/e94a60c378f7eeb7a704897cbe5c0580cef804e0)
