### ISSUE TITLE
Stack trace when clicking on Yes or No button to upgrade configuration

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#19]
When I click No and Yes buttons in the upgrade dialog, I get the following error. 

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 301, in login
    config_load_status = self.load_configuration_from_file()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 518, in load_configuration_from_file
    if self.configuration_file_updater.load():
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\settings\config_file_updater.py", line 846, in load
    self._rename_old_config_file(old_config_file, path)
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\settings\config_file_updater.py", line 184, in _rename_old_config_file
    os.rename(old_config_file, new_file)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party\\fontTools']
```

**Comment by geonomad-consulting** [comment]
It's not a path issue. It seems windows doesn't like semi colons in the file name. Current time stamp labeling outputs  stdmConfig2016-08-02 17:19:53.470103.xml

Let me check if there is a time stamp that is friendly to windows

**Comment by wondie** [comment]
Oh I see. So what about file_name.replace(':', '_')

**Comment by geonomad-consulting** [comment]
Using string version of time and date will be more appropriate. 

Fixed with this [commit](https://github.com/geonomad-consulting/stdm/commit/8ac305dab648497fe4613af738bc6307b29ecf71)

**Comment by wondie** [comment]
Still the stack trace was shown. But I when I tried `replace`, it worked. 

```
dt = str(datetime.datetime.now())
dt = dt.replace(':', '_')
```

**Comment by geonomad-consulting** [comment]
How about now. I have removed the semi colon and replace by underscore

**Comment by wondie** [comment]
It is now working. I would have been good to start with year and end with minute and to separate them with underscore.

**Comment by wondie** [comment]
This issue is now fixed.
