### ISSUE TITLE
Stack trace when upgrading old configuration with data

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#23]
I am getting the following error when I try to upgrade the old configuration with data. 

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 301, in login
    config_load_status = self.load_configuration_from_file()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 541, in load_configuration_from_file
    self.configuration_file_updater.backup_data()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\settings\config_file_updater.py", line 1120, in backup_data
    progress.setValue(i + 1)
TypeError: unsupported operand type(s) for +: 'RowProxy' and 'int'


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party\\fontTools']
```

**Comment by geonomad-consulting** [comment]
This is fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/eda3dd1f2d7b9365be29b5f034508485eb36ae68)

**Comment by wondie** [comment]
This issue is fixed.
