### ISSUE TITLE
(ProgrammingError) type "u" does not exist when importing data

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#34]
Please find the error message below. It seems **u** is not removed. I got it while it was importing data. 

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 304, in login
    config_load_status = self.load_configuration_from_file()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\plugin.py", line 575, in load_configuration_from_file
    self.configuration_file_updater.backup_data()
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\settings\config_file_updater.py", line 1398, in backup_data
    new_STR_data):
  File "C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins\stdm\data\pg_utils.py", line 212, in import_data
    result = conn.execute(t, **kwargs)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\sql\elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 958, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\util\compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\base.py", line 951, in _execute_context
    context)
  File "C:\PROGRA~1\QGISWI~1.3)F\apps\qgis\python\plugins\stdm\third_party\sqlalchemy\engine\default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) type "u" does not exist
LINE 1: ... 26, 81), (108, 1, 20, 21), (109, 1, 75, 6), (91, u'1', 7, 4...
                                                             ^
 "INSERT INTO ba_social_tenure_relationship (id, tenure_type, party_id, spatial_unit_id) VALUES (2, 3, 208, 47), (3, 4, 24, 47), (4, 4, 213, 47), (5, 4, 211, 47), (11, 3, 272, 60), (12, 3, 273, 60), (13, 4, 275, 60), (14, 4, 276, 60), (15, 4, 280, 60), (16, 4, 277, 60), (17, 6, 278, 60), (18, 6, 309, 60), (19, 6, 279, 60), (20, 6, 310, 60), (29, 1, 243, 28), (30, 6, 254, 28), (31, 4, 248, 28), (32, 4, 245, 28), (33, 4, 244, 28), (34, 4, 246, 28), (35, 4, 249, 28), (36, 4, 247, 28), (37, 6, 253, 28), (38, 6, 252, 28), (39, 6, 255, 28), (40, 6, 251, 28), (43, 4, 289, 59), (44, 4, 286, 59), (45, 1, 283, 59), (46, 5, 284, 59), (47, 4, 288, 59), (48, 4, 285, 59), (49, 4, 290, 59), (50, 4, 287, 59), (53, 1, 300, 55), (54, 7, 302, 56), (55, 4, 303, 56), (56, 1, 301, 56), (57, 1, 281, 52), (58, 6, 295, 97), (59, 6, 292, 97), (60, 6, 291, 97), (61, 6, 297, 97), (62, 1, 298, 97), (63, 6, 296, 97), (64, 6, 294, 97), (65, 1, 311, 58), (66, 1, 256, 54), (67, 1, 299, 31), (68, 1, 298, 61), (71, 1, 1, 25), (72, 5, 2, 25), (73, 4, 3, 25), (74, 4, 8, 25), (75, 4, 5, 25), (128, 1, 67, 4), (90, 3, 209, 47), (92, 1, 8, 32), (93, 5, 9, 32), (94, 4, 10, 32), (95, 6, 12, 32), (96, 4, 13, 32), (97, 6, 14, 32), (98, 6, 15, 32), (99, 6, 16, 32), (100, 6, 17, 32), (101, 6, 18, 32), (103, 1, 19, 71), (104, 1, 23, 81), (105, 4, 24, 81), (106, 4, 25, 81), (107, 4, 26, 81), (108, 1, 20, 21), (109, 1, 75, 6), (91, u'1', 7, 45), (110, 1, 7, 19), (112, 4, 271, 29), (113, 4, 268, 29), (114, 1, 266, 29), (115, 5, 267, 29), (116, 6, 269, 29), (117, 4, 312, 29), (118, 3, 33, 77), (119, 4, 34, 77), (120, 4, 35, 77), (121, 3, 32, 77), (122, 1, 36, 76), (123, 4, 37, 76), (124, 4, 38, 76), (125, 6, 39, 76), (126, 6, 40, 76), (127, 6, 41, 76), (129, 4, 69, 4), (130, 4, 70, 4), (131, 4, 71, 4), (132, 5, 68, 4), (133, 6, 72, 4), (134, 6, 74, 4), (135, 6, 73, 4), (137, 5, 45, 17), (138, 4, 47, 17), (139, 4, 48, 17), (140, 4, 49, 17), (141, 4, 51, 17), (142, 4, 50, 17), (143, 4, 52, 17), (145, 4, 54, 17), (147, 4, 56, 17), (148, 6, 57, 17), (149, 1, 53, 73), (150, 5, 45, 73), (151, 4, 49, 73), (152, 4, 51, 73), (153, 4, 54, 73), (154, 4, 46, 73), (155, 4, 56, 73), (156, 4, 55, 73), (157, 4, 47, 73), (158, 6, 57, 73), (159, 4, 52, 73), (160, 4, 48, 73), (161, 2, 58, 74), (162, 2, 59, 74), (163, 2, 60, 74), (164, 6, 61, 74), (165, 6, 62, 74), (166, 6, 63, 74), (167, 6, 64, 74), (169, 4, 46, 17), (168, 1, 53, 17), (170, 4, 55, 17), (171, 4, 313, 38), (172, 1, 78, 38), (173, 1, 79, 39), (174, 5, 80, 39), (175, 4, 81, 39), (176, 4, 87, 39), (177, 4, 88, 39), (179, 4, 90, 39), (181, 4, 92, 39), (183, 5, 80, 51), (178, 4, 97, 39), (180, 4, 91, 39), (182, 1, 79, 51), (184, 4, 92, 51), (185, 4, 88, 51), (186, 4, 90, 51), (187, 4, 97, 51), (188, 4, 91, 51), (189, 4, 87, 51), (190, 1, 79, 8), (191, 5, 80, 8), (192, 4, 92, 8), (193, 4, 97, 8), (194, 4, 88, 8), (195, 4, 90, 8), (196, 4, 91, 8), (197, 4, 87, 8), (200, 3, 109, 37), (201, 3, 121, 37), (202, 4, 122, 37), (203, 4, 123, 37), (204, 1, 149, 42), (205, 5, 150, 42), (206, 6, 151, 42), (207, 6, 152, 42), (208, 4, 153, 42), (209, 6, 163, 42), (210, 4, 314, 42), (211, 6, 162, 42), (212, 6, 156, 42), (213, 3, 139, 48), (214, 3, 145, 48), (215, 4, 141, 48), (216, 4, 147, 48), (217, 6, 143, 48), (218, 3, 139, 33), (219, 3, 145, 33), (220, 4, 147, 33), (221, 4, 141, 33), (222, 6, 143, 33), (223, 1, 149, 49), (224, 5, 150, 49), (225, 6, 151, 49), (226, 6, 152, 49), (227, 4, 153, 49), (228, 6, 162, 49), (229, 6, 163, 49), (230, 6, 156, 49), (231, 1, 315, 40), (232, 1, 129, 41), (233, 1, 129, 14), (234, 2, 317, 44), (235, 1, 124, 64), (236, 5, 125, 64), (237, 4, 126, 64), (238, 4, 127, 64), (239, 4, 128, 64), (240, 4, 167, 50), (241, 1, 171, 50), (242, 5, 165, 50), (243, 4, 169, 50), (244, 4, 172, 50), (245, 4, 168, 50), (246, 6, 170, 50), (247, 4, 166, 50), (248, 1, 199, 43), (249, 1, 199, 84), (250, 1, 234, 87), (251, 1, 233, 95), (252, 1, 235, 86), (253, 1, 241, 90), (254, 1, 240, 91), (255, 1, 239, 94), (256, 1, 238, 93), (257, 1, 237, 88), (258, 2, 317, 69)" {}


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, exported

Python path: ['C:/Users/Wondim/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python', u'C:/Users/Wondim/.qgis2/python', u'C:/Users/Wondim/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.3)F/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1.3)F\\bin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Wondim/.qgis2//python', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party', 'C:\\PROGRA~1\\QGISWI~1.3)F\\apps\\qgis\\python\\plugins\\stdm\\third_party\\fontTools']
```

**Comment by geonomad-consulting** [comment]
I think this has been fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/c2fd5f96bee5636622e788459662d014371dc77b)

**Comment by geonomad-consulting** [comment]
@wondie did you test this issue, since I can't replicate it on my setup?

**Comment by wondie** [comment]
Ok I am not sure on which database that error happened but once the newer issues are fixed, I can replicate it and update you.

**Comment by geonomad-consulting** [comment]
Is is still an issue?

**Comment by wondie** [comment]
I haven't tested yet. Let me test and report back.

**Comment by wondie** [comment]
Ok, I tried to see the issue but currently, no data is being backed up into the social tenure table where this issue lies. I will report back when issue #37 is fixed.

**Comment by wondie** [comment]
I can close this issue for now as I couldn't see it anymore too.
